service:
  name: sans-server-todo-app-jtg72006
frameworkVersion: '2'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb-local
provider:
  apiGateway:
    shouldStartNameWithService: true

  tracing:
    lambda: true
    apiGateway: true
    
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region,'us-west-2'}

  environment:
    PHOTO_BUCKET: sans-server-todo-jtg72006-${self:provider.stage}
    TODOS_TABLE: TodosDB-${self:provider.stage}
    INDEX_NAME: TodoIDindex
    BUCKET_EXPIRATION: 600

  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - codedeploy:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: arn:aws:s3:::${self:provider.environment.PHOTO_BUCKET}/*

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: "8000"
      inMemory: true
      migrate: true
  serverless-offline:
    httpPort: 3003
  documentation:
    api:
      info:
        version: v0.1.0
        title: JTG Todo
        description: Serverless application for things todo.



functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  OnlineCheck:
    handler: src/lambda/http/onlineCheck.handler
    events:
      - http:
          method: get
          cors: true
          path: test

  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      - http:
          method: get
          path: todos
          cors: true
          authorizer: Auth     
    iamRoleStatements:
      - Effect: Allow
        Action:
          - 'logs:Create*'
          - 'logs:PutLogEvents'
        Resource:
          - 'arn:aws:logs:${self:provider.region}:*:*'
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}'
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:Scan
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}/index/${self:provider.environment.INDEX_NAME}'

  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      - http:
          method: post
          path: todos
          cors: true
          authorizer: Auth
          request:
            schema:
              application/json: ${file(src/validation/createTodo.json)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}'


  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      - http:
          method: patch
          path: todos/{todoId}
          cors: true
          authorizer: Auth
          request:
            schema:
              application/json: ${file(src/validation/updateTodo.json)}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}'


  DeleteTodo:
    handler: src/lambda/http/deleteTodo.handler
    events:
      - http:
          method: delete
          path: todos/{todoId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}'

  # TODO: Configure this function
  # Needs IAM permissions to access Buckets/Databases
  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: todos/{todoId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: 'arn:aws:s3:::${self:provider.environment.PHOTO_BUCKET}/*'

resources:
  Resources:
    # TODO: Add any necessary AWS resources
    GatewayResponseDefault4XX:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS,POST'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
    # An S3 Bucket
    PhotoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PHOTO_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: Photobucket-Policy-1
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadWriteBucketPolicy
              Effect: Allow
              Principal: '*'
              Action: 
                - 's3:GetObject'
                - 's3:PutObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.PHOTO_BUCKET}/*'
        Bucket: !Ref PhotoBucket

    # A Dynamo Database probably
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
          AttributeDefinitions:
            - AttributeName: userId
              AttributeType: S
            - AttributeName: createdAt
              AttributeType: S
            - AttributeName: todoId
              AttributeType: S
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: todoId
              KeyType: RANGE
          BillingMode: PAY_PER_REQUEST
          TableName: ${self:provider.environment.TODOS_TABLE}
          LocalSecondaryIndexes:
            - IndexName: ${self:provider.environment.INDEX_NAME}
              KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: createdAt
                  KeyType: RANGE
              Projection:
                ProjectionType: ALL